<h2><?= $this->translate('You have requested password recovery option for email') ?>&nbsp;<?= $this->email ?></h2>
<p>
    <?= $this->translate('To recover password go to') ?>
    <a href="<?= $this->url('recovery-password', ['hash' => $this->hash], ['force_canonical' => true]) ?>"><?= $this->translate('url') ?></a>
    <br>
    <?= $this->translate('If you did not request a password recovery follow') ?>
    <a href="<?= $this->url('recovery-password-cancel', ['hash' => $this->hash], ['force_canonical' => true]) ?>"><?= $this->translate('url') ?></a>
</p>