<?php

namespace Application\Back;

use Zend\Authentication\Storage\Session as StorageSession;

/**
 * Class Session
 * @package Application\Back
 */
class Session extends StorageSession
{

    /**
     * @return
     */
    public function read()
    {
        return parent::read(); // TODO: Change the autogenerated stub
    }


}