<form id="select-language" action="<?= $this->url('index', ['action' => 'lang']) ?>" class="navbar-right"  style="display:inline-block; margin-right: 10px; margin-top: 8px; margin-bottom: 8px;">
    <div style="display:inline-block">
            <select name="language" id="lang-selector" class="form-control input-md application-input"  style="color: #91BF21; ">
            <?php foreach ($this->locale()->getList() as $key => $value) :?>
                <option value="<?= $key ?>" <?php if ($this->locale()->getCurrentLocale() === $key) echo "selected=\"selected\"" ?>><?= $value ?></option>
            <?php endforeach; ?>
        </select>
    </div>
</form>