<script src="<?= $this->basePath('js/vendor/require.js') ?>"></script>
<script>
    var marker;
    'use strict';

    requirejs(['<?= $this->basePath('js/vendor/jquery-3.1.0.min.js') ?>'], function() {
        requirejs(['<?= $this->basePath('js/vendor/bootstrap.min.js') ?>'], function() {
            requirejs(['<?= $this->basePath('js/vendor/bootstrap-datepicker.js') ?>'], function() {
                requirejs(['<?= $this->basePath('js/application.js') ?>'], function() {
                    require(['<?= $this->basePath('js/google-map.js') ?>'], function(Map) {
                        jQuery('document').ready(function () {
                            var map = Map.init();

                            google.maps.event.addListener(map, 'click', function(event) {
                                Map.clearMarker();
                                Map.addMarker(map, event.latLng.lat(), event.latLng.lng());
                                document.getElementById('latitude').value = event.latLng.lat();
                                document.getElementById('longitude').value = event.latLng.lng();
                            });
                        });

                        jQuery(document).on('click', '.update-marker', function (event) {
                            event.defaultPrevented = true;

                            return false;
                        });
                    });
                });
            });
        });
    });
</script>
