<script src="<?= $this->basePath('js/vendor/require.js') ?>"></script>
<script>

    'use strict';

    var Globals = {};

    <?php $routeMatch = $this->route(); ?>
    <?php /** @var \Application\View\Helper\Route $routeMatch */ ?>
    <?php $url = $this->url($routeMatch->getRoute(), $routeMatch->getParams()); ?>
    <?php $scripts = $this->scripts();?>
    <?php $scriptFiles = []; ?>
    <?php foreach ($scripts as $rule => $script) : ?>

        <?php if (preg_match('/' . $rule . '/', $url) === 1) : ?>
            <?php $scriptFiles = array_merge($scriptFiles, $script) ?>
        <?php endif; ?>

    <?php endforeach; ?>

    <?php foreach ($scriptFiles as $scriptFile) : ?>
        requirejs(['<?= $this->basePath($scriptFile) ?>'], function () {
    <?php endforeach; ?>
    <?= str_repeat('});', count($scriptFiles)) ?>

</script>
