<!-- Le styles -->
<?= $this->headLink(['rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'])
    ->prependStylesheet($this->basePath('css/style.css'))
    ->prependStylesheet($this->basePath('css/jquery.loading.min.css'))
    ->prependStylesheet($this->basePath('css/bootstrap-datepicker.css'))
    ->prependStylesheet($this->basePath('css/bootstrap.min.css'))
?>
