<div class="row">
    <form action="<?= $this->url('dashboard', ['action' => 'areas']) ?>" class="async col-md-3 collapse" id="add-area-around">
        <div class="form-group">
            <label class="control-label application-label" for="area_value"><?= $this->translate('Set Area Around') ?>*</label>
            <input id="area_value" name="area_value" type="text" placeholder="km" class="form-control input-md application-input" required/>
        </div>
        <button class="batton-save btn">Create area</button>
    </form>
</div>
<a type="button" class="row a-dashboard" data-toggle="collapse" data-target="#add-area-around">+ Set area around</a>
<table class="table">
    <tr>
        <th>#</th>
        <th>Text Value</th>
        <th>Value in meters</th>
    </tr>
        <?php foreach ($this->paginator as $area) : ?>
            <tr>
                <?php /** @var \Application\Model\Area $area */ ?>
                <td><?= $area->getId() ?></td>
                <td><?= $area->getValue() ?></td>
                <td><?= $area->getIntValue() ?></td>
            </tr>
            <?php endforeach; ?>
</table>
<div class="text-right">
    <?= $this->render('layout/helper/pagination') ?>
</div>