<form action="<?= $this->url('dashboard', ['action' => 'overview']) ?>" class=""  method="post" id="filter_overview" >
    <div class="row">
        <div class="form-group col-md-3">
            <label class="control-label application-label" for="name_field"><?= $this->translate('Name') ?></label>
            <input id="name_field" name="name" type="text" value="" placeholder="" class="form-control input-md application-input">
        </div>
        <div class="form-group col-md-3">
            <label class="control-label application-label" for="surname_field"><?= $this->translate('Surname') ?></label>
            <input id="surname_field" name="surname" value="" type="text" placeholder="" class="form-control input-md application-input">
        </div>

        <div class="form-group col-md-3">
            <label class="control-label application-label" for="zip_field"><?= $this->translate('ZIP') ?></label>
            <input id="zip_field" name="zip" type="text" value="" placeholder="" class="form-control input-md application-input">
        </div>

        <div class="form-group col-md-3">
            <label class="control-label application-label" for="city_field-search"><?= $this->translate('City') ?></label>
            <input id="city_field-search" name="city" type="text" value="" placeholder="" class="form-control input-md application-input">
        </div>

        <div class="form-group col-md-3">
            <label class="control-label application-label" for="start_day_field"><?= $this->translate('Date') ?></label>

            <div class="" id="sandbox-container">
                <div class="input-daterange input-group" id="datepicker">
                    <input type="text" class="form-control input-md application-input" name="start" value="">
                    <span class="input-group-addon button-save">to</span>
                    <input type="text" class="form-control input-md application-input" name="end" value="">
                </div>
            </div>
        </div>

        <div class="form-group col-md-3">
            <label class="control-label application-label" for="driving_license_field"><?= $this->translate('Driving licence') ?></label>
            <select id="driving_license_field" name="driving_license" class="form-control application-input">
                <option value="" selected></option>
                <option value="1" <?= isset($this->fields['driving_license']) && $this->fields['driving_license'] == '1' ? 'selected' : '' ?>><?= $this->translate('Yes') ?></option>
                <option value="0" <?= isset($this->fields['driving_license']) && $this->fields['driving_license'] == '0' ? 'selected' : '' ?>><?= $this->translate('No') ?></option>
            </select>
        </div>

        <div class="form-group col-md-3">
            <label class="control-label application-label" for="car_available_field"><?= $this->translate('Car available') ?></label>
            <select id="car_available_field" name="car_available" class="form-control application-input">
                <option value="" selected></option>
                <option value="1" <?= isset($this->fields['car_available']) && $this->fields['car_available'] == '1' ? 'selected' : '' ?>><?= $this->translate('Yes') ?></option>
                <option value="0" <?= isset($this->fields['car_available']) && $this->fields['car_available'] == '0' ? 'selected' : '' ?>><?= $this->translate('No') ?></option>
            </select>
        </div>
    </div>

    <input type="hidden" class="" id="sort-column-name" name="column_sort_name" value="">
    <input type="hidden" class="" id="sort-order"  name="column_sort_order" value="">
    <div class="row">
        <div class="form-group">
            <button class="btn button-save">Search</button>
        </div>
    </div>
</form>

<?php if ($this->paginator->count() === 0) : ?>
    <div class="text-center text-muted">
        <h3><?= $this->translate('Nothing where found') ?></h3>
    </div>
<?php else :?>

    <table class="table" id="overview_table">
        <thead>
            <tr>
                <th data-column-name="id">#</th>
                <th data-column-name="created"><?= $this->translate('Date of application / entry') ?></th>
                <th data-column-name="name"><?= $this->translate('Name') ?></th>
                <th data-column-name="surname"><?= $this->translate('Surname') ?></th>
                <th data-column-name="zip"><?= $this->translate('ZIP') ?></th>
                <th data-column-name="city"><?= $this->translate('City') ?></th>
                <th data-column-name="mobilePhone"><?= $this->translate('Mobile Phone') ?></th>
            </tr>
        </thead>
        <?php foreach ($this->paginator as $employee) : ?>
            <tr>
                <?php /** @var \Application\Model\Employee $employee */ ?>
                <td><?= $employee->getId() ?></td>
                <td><?= $employee->getCreated()->format('Y-m-d') ?></td>
                <td>
                    <a
                        href="#"
                        class="modal-action"
                        data-action="<?= $this->url('show-employee', ['id' => $employee->getId()] ) ?>"
                        data-element="#modal-action"
                        >
                        <?= $employee->getName() ?>
                    </a>
                </td>
                <td><?= $employee->getSurname() ?></td>
                <td><?= $employee->getZip() ?></td>
                <td><?= $employee->getCity() ?></td>
                <td><?= $employee->getMobilePhone() ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif; ?>
<div class="text-right">
    <?= $this->render('layout/helper/pagination') ?>
</div>