<form action="<?= $this->url('dashboard', ['action' => 'search']) ?>" class="async" >
    <div class="row">
        <div class="col-md-3">
            <div class="form-group ">
                <input id="name_search" name="name" type="text" placeholder="<?= $this->translate('Name') ?>" class="form-control input-md application-input" required/>
            </div>
        </div>
        <a type="button" class="row" data-toggle="collapse" data-target="#add-area-around">Advanced</a>
    </div>

    <div class="collapse" id="add-area-around" >
dfgdfgdfg
    </div>

    <div class="form-group">
        <button>Search</button>
    </div>
</form>


<table class="table">
    <tr>
        <th>#</th>
        <th>Name</th>
        <th>Mobile Phone</th>
        <th>Address</th>
    </tr>
    <?php foreach ($this->paginator as $employee) : ?>
        <tr>
            <?php /** @var \Application\Model\Employee $employee */ ?>
            <td><?= $employee->getId() ?></td>
            <td>
                <a
                    href="#"
                    class="modal-action"
                    data-action="<?= $this->url('show-employee', ['id' => $employee->getId()] ) ?>"
                    data-element="#modal-action"
                    >
                    <?= $employee->getName() ?>
                </a>
            </td>

            <td><?= $employee->getMobilePhone() ?></td>
            <td><?= $employee->getAddress() ?></td>
        </tr>
    <?php endforeach; ?>

</table>
<div class="text-right">
    <?= $this->render('layout/helper/pagination') ?>
</div>