<form action="<?= $this->url('dashboard', ['action' => 'search']) ?>" class=""  method="post">
    <div class="row">
        <div class="form-group col-md-3">
            <label class="control-label application-label" " for="name_field"><?= $this->translate('Name') ?></label>
            <input id="name_field" name="name" type="text" value="<?= isset($this->fields['name']) ? $this->fields['name'] : '' ?>" placeholder="" class="form-control input-md application-input">
        </div>

        <div class="collapse <?= isset($this->fields['surname']) ? 'in' : '' ?>" id="add-area-around" >
            <div class="form-group col-md-3">
                <label class="control-label application-label" for="surname_field"><?= $this->translate('Surname') ?></label>
                <input id="surname_field" name="surname" value="<?= isset($this->fields['surname']) ? $this->fields['surname'] : '' ?>" type="text" placeholder="" class="form-control input-md application-input">
            </div>

            <div class="form-group col-md-3">
                <label class="control-label application-label" for="city_field"><?= $this->translate('City') ?></label>
                <input id="city_field" name="city" type="text" value="<?= isset($this->fields['city']) ? ($this->fields['city']) : '' ?>" placeholder="" class="form-control input-md application-input">
            </div>

            <div class="form-group col-md-3">
                <label class="control-label application-label" for="address_field"><?= $this->translate('Address') ?></label>
                <input id="address_field" name="address" type="text" value="<?= isset($this->fields['address']) ? ($this->fields['address']) : '' ?>" placeholder="" class="form-control input-md application-input">
            </div>

            <div class="form-group col-md-3">
                <label class="control-label application-label" for="zip_field"><?= $this->translate('ZIP') ?></label>
                <input id="zip_field" name="zip" type="text" value="<?= isset($this->fields['zip']) ? ($this->fields['zip']) : '' ?>" placeholder="" class="form-control input-md application-input">
            </div>

            <div class="form-group col-md-3">
                <label class="control-label application-label" for="mobile_phone_field"><?= $this->translate('Mobile phone number') ?></label>
                <input id="mobile_phone_field" name="mobile_phone" type="text" value="<?= isset($this->fields['mobile_phone']) ? ($this->fields['mobile_phone']) : '' ?>" placeholder="" class="form-control input-md application-input">
            </div>

            <div class="form-group col-md-3">
                <label class="control-label application-label" for="landline_number_field"><?= $this->translate('Landline number') ?></label>
                <input id="landline_number_field" name="landline_phone" value="<?= isset($this->fields['landline_phone']) ? ($this->fields['landline_phone']) : '' ?>" type="text" placeholder="" class="form-control input-md application-input">
            </div>

            <div class="form-group col-md-3">
                <label class="control-label application-label" for="email_field"><?= $this->translate('Email') ?></label>
                <input id="email_field" name="email" type="text" value="<?= isset($this->fields['email']) ? ($this->fields['email']) : '' ?>" placeholder="" class="form-control input-md application-input">
            </div>

            <div class="form-group col-md-3">
                <label class="control-label application-label" for="area_around_field"><?= $this->translate('Area around') ?></label>
                <select id="area_around_field" name="area_around" class="form-control application-input">
                    <option value="" selected></option>
                    <?php foreach ($this->areas as $area) : ?>
                        <?php /** @var \Application\Model\Area $area */ ?>
                        <option value="<?= $area->getId() ?>" <?= isset($this->fields['area_around']) && $this->fields['area_around'] == $area->getId() ? 'selected' : '' ?>><?= $area->getValue() ?></option>
                    <?php endforeach; ?>
                </select>
            </div>

            <div class="form-group col-md-3">
                <label class="control-label application-label" for="contact_type_field"><?= $this->translate('Type of contract') ?></label>
                <select id="contact_type_field" name="contract_type" class="form-control application-input">
                    <option value="" selected></option>
                    <?php foreach ($this->contracts as $contract) : ?>
                        <?php /** @var \Application\Model\Contract $contract */ ?>

                        <option value="<?= $contract->getId() ?>" <?= isset($this->fields['contract_type']) && $this->fields['contract_type'] == $contract->getId() ? 'selected' : '' ?>><?= $contract->getName() ?></option>
                    <?php endforeach; ?>
                </select>
            </div>

            <div class="form-group col-md-3">
                <label class="control-label application-label" for="weekly_hours_field"><?= $this->translate('Weekly hours available') ?></label>
                <select id="weekly_hours_field" name="weekly_hours" class="form-control application-input">
                    <option value="" selected></option>
                    <?php foreach ($this->weeklyHours as $weeklyHour) : ?>
                        <?php /** @var \Application\Model\WeeklyHours $weeklyHour */ ?>
                        <option value="<?= $weeklyHour->getId() ?>" <?= isset($this->fields['weekly_hours']) && $this->fields['weekly_hours'] == $weeklyHour->getId() ? 'selected' : '' ?>>
                            <?= $weeklyHour->getValue() ?></option>
                    <?php endforeach; ?>
                </select>
            </div>

            <div class="form-group col-md-3">
                <label class="control-label application-label" for="start_day_field"><?= $this->translate('Date') ?></label>

                <div class="" id="sandbox-container">
                    <div class="input-daterange input-group" id="datepicker">
                        <input type="text" class="form-control input-md application-input" name="start" value="<?= isset($this->fields['start']) ? ($this->fields['start']) : '' ?>">
                        <span class="input-group-addon">to</span>
                        <input type="text" class="form-control input-md application-input" name="end" value="<?= isset($this->fields['end']) ? ($this->fields['end']) : '' ?>">
                    </div>
                </div>
            </div>

            <div class="form-group col-md-3">
                <label class="control-label application-label" for="hourly_rate_field"><?= $this->translate('Hourly rate') ?></label>
                <input id="hourly_rate_field" name="hourly_rate" type="text" value="<?= isset($this->fields['hourly_rate']) ? ($this->fields['hourly_rate']) : '' ?>" placeholder="" class="form-control input-md application-input">
            </div>

            <div class="form-group col-md-3">
                <label class="control-label application-label" for="experience_field"><?= $this->translate('Experience in the job') ?></label>
                <select id="experience_field" name="experience" class="form-control application-input">
                    <option value="" selected></option>
                    <option value="1" <?= isset($this->fields['experience']) && $this->fields['experience'] == '1' ? 'selected' : '' ?>><?= $this->translate('Yes') ?></option>
                    <option value="0" <?= isset($this->fields['experience']) && $this->fields['experience'] == '0' ? 'selected' : '' ?>><?= $this->translate('No') ?></option>
                </select>
            </div>

            <div class="form-group col-md-3">
                <label class="control-label application-label" for="driving_licence_field"><?= $this->translate('Driving licence') ?></label>
                <input type="checkbox" name="driving_license" <?= isset($this->fields['driving_license']) && $this->fields['driving_license'] ? 'checked' : '' ?> value="1" id="driving_licence_field" >
            </div>

            <div class="form-group col-md-3">
                <label class="control-label application-label" for="car_available_field"><?= $this->translate('Car available') ?></label>
                <input type="checkbox" name="car_available" <?= isset($this->fields['car_available']) && $this->fields['car_available'] ? 'checked' : '' ?> value="1" id="car_available_field" >
            </div>

            <div class="form-group">
                <label class="control-label application-label" for="latitude_field"><?= $this->translate('latitude') ?></label>
                <input id="latitude" name="latitude" type="text" placeholder="" class="form-control input-md application-input">
            </div>

            <div class="form-group">
                <label class="control-label application-label" for="longitude_field"><?= $this->translate('longitude') ?></label>
                <input id="longitude" name="longitude" type="text" placeholder="" class="form-control input-md application-input">
            </div>
        </div>

        </div>
        <div class="collapse in" id="map-container">
            <div id="map" class="map frame"></div>
        </div>
        <a type="button" class="row" data-toggle="collapse" data-target="#map-container">Show map</a>


    <div class="row">
        <div class="form-group ">
            <button>Search</button>
        </div>
    </div>
    <a type="button" class="row" data-toggle="collapse" data-target="#add-area-around">Advanced</a>
</form>

<?php if ($this->paginator->count() === 0) : ?>
    <div class="text-center text-muted">
        <h3><?= $this->translate('Nothing where found') ?></h3>
    </div>
<?php else :?>
    <table class="table">
        <tr>
            <th>#</th>
            <th><?= $this->translate('Name') ?></th>
            <th><?= $this->translate('Mobile Phone') ?></th>
            <th><?= $this->translate('Address') ?></th>

        </tr>
        <?php foreach ($this->paginator as $employee) : ?>
            <tr>
                <?php /** @var \Application\Model\Employee $employee */ ?>
                <td><?= $employee->getId() ?></td>
                <td>
                    <a
                        href="#"
                        class="modal-action"
                        data-action="<?= $this->url('show-employee', ['id' => $employee->getId()] ) ?>"
                        data-element="#modal-action"
                        >
                        <?= $employee->getName() ?>
                    </a>
                </td>

                <td><?= $employee->getMobilePhone() ?></td>
                <td><?= $employee->getAddress() ?></td>
            </tr>
        <?php endforeach; ?>
    </table>
<?php endif; ?>
<div class="text-right">
    <?= $this->render('layout/helper/pagination') ?>
</div>