<form action="<?= $this->url('dashboard', ['action' => 'search']) ?>" class="search-employees"  method="post" id="filter-employee-form">
    <div class="row">

        <div class="form-group col-md-3">
            <label class="control-label application-label" for="location"><?= $this->translate('Office location') ?></label>
            <select id="location" name="location" class="form-control application-input">
                    <option value="" selected></option>
                <?php if($this->locationSelect) :?>
                    <?php foreach ($this->locationSelect as $value) :?>
                        <option>
                            <?= $value ?>
                        </option>
                    <?php endforeach;?>
                <?php endif;?>
            </select>
        </div>

        <div class="form-group col-md-3">
            <label class="control-label application-label" for="nat_speed"><?= $this->translate('Typing Speed (net speed)') ?></label>
            <select id="nat_speed" name="nat_speed" class="form-control application-input">
                <option value="" selected></option>
                <option value="-20"> Less than 20</option>
                <option value="20-30"> 20-30</option>
                <option value="31-40"> 31-40</option>
                <option value="41-50"> 41-50</option>
                <option value="51-60"> 51-60</option>
                <option value="61-70"> 61-70</option>
                <option value="+70"> 70+</option>
            </select>
        </div>

        <div class="form-group col-md-3">
            <label class="control-label application-label" for="pay"><?= $this->translate('Pay Expectation') ?></label>
            <select id="pay" name="pay" class="form-control application-input">
                <option value="" selected></option>
                <option value="8-9">$8.00-$9.00</option>
                <option value="9-9.50">$9.01-$9.50</option>
                <option value="9.50-10.00">$9.51-$10.00</option>
                <option value="10-11">$10.01-$11.00</option>
                <option value="11-12">$11.00-$12.00</option>
                <option value="12-13">$12.00-$13.00</option>
                <option value="+13">$13.01+</option>
            </select>
        </div>

        <div class="form-group col-md-3">
            <label class="control-label application-label" for="area_around_field"><?= $this->translate('Distance from Office') ?></label>
            <select id="area_around_field" name="area_around" class="form-control application-input">
                <option value="" selected></option>
                <?php foreach ($this->areas as $area) : ?>
                    <?php /** @var \Application\Model\Area $area */ ?>
                    <option value="<?= $area->getId() ?>" <?= isset($this->fields['area_around']) && $this->fields['area_around'] == $area->getId() ? 'selected' : '' ?>><?= $area->getValue() ?></option>
                <?php endforeach; ?>
            </select>
        </div>

        <div class="form-group col-md-3">
            <label class="control-label application-label" for="work_mlob"><?= $this->translate('Worked in a License Office Before') ?></label>
            <select id="work_mlob" name="work_mlob" class="form-control application-input">
                <option value="" selected></option>
                <option value="1" <?= isset($this->fields['driving_license']) && $this->fields['driving_license'] == '1' ? 'selected' : '' ?>><?= $this->translate('Yes') ?></option>
                <option value="0" <?= isset($this->fields['driving_license']) && $this->fields['driving_license'] == '0' ? 'selected' : '' ?>><?= $this->translate('No') ?></option>
            </select>
        </div>

        <div class="form-group col-md-3">
            <label class="control-label application-label" for="location"><?= $this->translate('Office location') ?></label>
            <select id="location" name="location" class="form-control application-input">
                <option value="" selected></option>
                <?php if($this->positionApplyingSelect) :?>
                    <?php foreach ($this->positionApplyingSelect as $value) :?>
                        <option>
                            <?= $value ?>
                        </option>
                    <?php endforeach;?>
                <?php endif;?>
            </select>
        </div>

        <div class="form-group col-md-3">
            <label class="control-label application-label" for="weekly_hours_field"><?= $this->translate('Hours Available Per Week') ?></label>
            <select id="weekly_hours_field" name="weekly_hours" class="form-control application-input">
                <?php foreach ($this->weeklyHours as $weeklyHour) : ?>
                    <option value="" selected></option>
                    <?php /** @var \Application\Model\WeeklyHours $weeklyHour */ ?>
                    <option
                            value="<?= $weeklyHour->getId() ?>"
                        <?= (isset($this->employee) && $this->employee->getWeeklyHoursAvailable() !== null && $this->employee->getWeeklyHoursAvailable()->getId() === $weeklyHour->getId()) ? 'selected' : '' ?>
                    >
                        <?= $weeklyHour->getValue() ?>
                    </option>
                <?php endforeach; ?>
            </select>
        </div>

        <div class="form-group col-md-3">
            <label class="control-label application-label" for="work_weekends_field"><?= $this->translate('Work Weekends?') ?></label>
            <select id="work_weekends_field" name="work_weekends" class="form-control application-input">
                <option value="" selected> </option>
                <option >No</option>
                <option >Every other</option>
                <option >All</option>
            </select>
        </div>

        <div class="form-group col-md-3">
            <label class="control-label application-label" for="customer_service_expierence"><?= $this->translate('Customer Service Experience') ?></label>
            <select id=customer_service_expierence" name="customer_service_expierence" class="form-control application-input">
                <option value="" selected> </option>
                <?php if($this->expireenceSelect) :?>
                    <?php foreach ($this->expireenceSelect as $value) :?>
                        <option>
                            <?= $value ?>
                        </option>
                    <?php endforeach;?>
                <?php endif;?>
            </select>
        </div>


        <div class="form-group col-md-3">
            <label class="control-label application-label" for="business_operations_expierence"><?= $this->translate('Business Operations') ?></label>
            <select id="business_operations_expierence" name="business_operations_expierence" class="form-control application-input">
                <option value="" selected> </option>
                <?php if($this->expireenceSelect) :?>
                    <?php foreach ($this->expireenceSelect as $value) :?>
                        <option>
                            <?= $value ?>
                        </option>
                    <?php endforeach;?>
                <?php endif;?>
            </select>
        </div>



        <div class="form-group col-md-3">
            <label class="control-label application-label" for="management_expierence"><?= $this->translate('Management Experience') ?></label>
            <select id="management_expierence" name="management_expierence" class="form-control application-input">
                <option selected> </option>
                <?php if($this->expireenceSelect) :?>
                    <?php foreach ($this->expireenceSelect as $value) :?>
                        <option>
                            <?= $value ?>
                        </option>
                    <?php endforeach;?>
                <?php endif;?>
            </select>
        </div>

        <div class="form-group col-md-3">
            <label class="control-label application-label" for="status_field"><?= $this->translate('Status') ?></label>
            <select id="status_field" name="status" class="form-control application-input">
                <option value="" selected><?= $this->translate('Any') ?></option>
                <option value="active"><?= $this->translate('Active') ?></option>
                <option value="deleted"><?= $this->translate('Deleted') ?></option>
                <option value="employed"><?= $this->translate('Employed') ?></option>
            </select>
        </div>

        <div class="form-group col-md-3">
            <label class="control-label application-label" for="zip_field"><?= $this->translate('Search address marker') ?></label>
            <div class="input-group" id="">
                <input id="zip_field" name="zip" type="text" value="<?= isset($this->fields['zip']) ? ($this->fields['zip']) : '' ?>" placeholder="" class="form-control input-md application-input">
                <span class="input-group-addon button-save"><?= $this->translate('range') ?></span>
                <input type="number" class="form-control input-md application-input" name="range" placeholder="<?= $this->translate('km')?>" title="<?= $this->translate('range in ml')?>" step="0.1">
            </div>
        </div>


        <input id="latitude" name="latitude" type="hidden" placeholder="" class="form-control input-md application-input" value="<?= isset($this->fields['latitude']) ? ($this->fields['latitude']) : '' ?>">
        <input id="longitude" name="longitude" type="hidden" placeholder="" class="form-control input-md application-input" value="<?= isset($this->fields['longitude']) ? ($this->fields['longitude']) : '' ?>">
        <input id="page-number" type="hidden" name="page">
    </div>
    <div class="row">
        <div class="form-group">
            <button class="btn button-save" style="margin-left: 15px"><?= $this->translate('Search') ?></button>
            <div id="clear_marker" class="btn button-save" style="margin-left: 15px;"><?= $this->translate('Clear marker') ?></div>
        </div>
    </div>
</form>
<div class="collapse in" id="map-container">
    <div id="map" class="map frame"></div>
</div>
<div id="employees-list">
    <?= $this->render('layout/concern/employees') ?>
</div>
