<form action="<?= $this->url('dashboard', ['action' => 'statistics']) ?>" id="filter-employee-form" filter-employee-form class="statistics-form row" method="post" >
    <div class="form-group col-md-3">
        <label class="control-label application-label" for="statistic_date"><?= $this->translate('Select statistic period') ?></label>
        <select id="statistic_date" name="statistic_date" class="form-control application-input statistic" data-action="<?= $this->url('dashboard', ['action' => 'statistics']) ?>">
            <option value="" selected >ALL</option>
            <option value="7" <?= (isset($post['statistic_date']) && $post['statistic_date'] == '7') ? 'selected' : '' ?> >Last 7</option>
            <option value="14" <?= (isset($post['statistic_date']) && $post['statistic_date'] == '14') ? 'selected' : '' ?>>Last 14</option>
            <option value="30" <?= (isset($post['statistic_date']) && $post['statistic_date'] == '30') ? 'selected' : '' ?>>Last 30</option>
        </select>
    </div>
    <input type="hidden" name="page" id="page-number">
</form>
<div class="row">
    <h5>Total applications<?= (isset($post['statistic_date']) && !empty($post['statistic_date'])) ? (' where recieved within the last ' . $post['statistic_date'] . ' days:') : ': ' ?>
        <strong><?=$this->paginator->getTotalItemCount() ?></strong>
    </h5>
</div>
<div id="employees-list">
    <?= $this->render('layout/concern/employees') ?>
</div>
