<div class="row">
    <form action="<?= $this->url('dashboard', ['action' => 'weekly-hours']) ?>" class="async col-md-3 collapse" id="weekly-hours-add-collapse">
        <div class="form-group">
            <label class="control-label application-label" for="weekly-hours-add"><?= $this->translate('Set Weekly hours') ?>*</label>
            <input id=weekly-hours-add" name="value" type="text" placeholder="" class="form-control input-md application-input" required/>
        </div>
        <button class="batton-save btn">Create area</button>
    </form>
</div>
<a type="button" class="row a-dashboard" data-toggle="collapse" data-target="#weekly-hours-add-collapse">+ Set Weekly hours</a>
<table class="table">
    <tr>
        <th>#</th>
        <th>Value</th>
        <th>Integer value</th>
        <th></th>
    </tr>
        <?php foreach ($this->paginator as $WH) : ?>
            <tr>
                <?php /** @var \Application\Model\Area $area */ ?>
                <td><?= $WH->getId() ?></td>
                <td class="value-name"><?= $WH->getValue() ?></td>
                <td><?= $WH->getIntValue() ?></td>
                <td>
                    <div class="text-right configure-buttons" data-id="<?= $WH->getId() ?>" data-action="/dashboard/weekly-hours-delete" data-action-save="/dashboard/weekly-hours">
                        <a class="btn a-dashboard  configure-edit"><span class="glyphicon glyphicon-edit" aria-hidden="true"></span> Edit</a>&nbsp;
                        <a class="btn a-dashboard configure-delete"><span class="glyphicon glyphicon-trash" aria-hidden="true"> Delete</a>
                    </div>
                </td>
            </tr>
            <?php endforeach; ?>
</table>
<div class="text-right">
    <?= $this->render('layout/helper/pagination') ?>
</div>