<?= $this->doctype() ?>

<html lang="en">
    <head>
        <meta charset="utf-8">
        <?= $this->headTitle('Employee Application')->setSeparator(' - ')->setAutoEscape(false) ?>
        <?= $this->render('layout/header/meta') ?>
        <?= $this->render('layout/header/styles') ?>
        <?= $this->render('layout/header/scripts') ?>


    </head>
    <body>
        <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a class="navbar-brand" href="#">Company</a>
                </div>
                <?= $this->render('layout/menu/' . ($this->user === null ? 'guest' : 'user') . '.phtml') ?>
            </div>
        </nav>
        <div class="container">
            <?= $this->content ?>
            <hr>
            <footer>
                <p>&copy; 2005 - <?= date('Y') ?> by Zend Technologies Ltd. All rights reserved.</p>
            </footer>
        </div>
    </body>
</html>
