<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <form class="async" action="<?= $this->url('user', ['action' => 'login']) ?>" method="post">
            <div class="form-group">
                <label for="email_field">Email</label>
                <input type="text" name="email" id="email_field" class="form-control">
            </div>
            <div class="form-group">
                <label for="password_field">Password</label>
                <input type="password" name="password" id="password_field" class="form-control">
            </div>
            <div class="text-right">
                <button class="btn btn-default">Log in</button>
            </div>
        </form>
    </div>
</div>