<div class="row">


        <ul class="nav nav-tabs nav-justified">
            <li class="active"><a data-toggle="tab" href="#step_1">Step 1</a></li>
            <li><a data-toggle="tab" href="#step_2">Step 2</a></li>
            <li><a data-toggle="tab" href="#step_3">Step 3</a></li>
            <li><a data-toggle="tab" href="#step_4">Step 4</a></li>
            <li><a data-toggle="tab" href="#step_5">Step 5</a></li>
        </ul>

            <div class="tab-content">

                <!-- STEP 1-->
                <div id="step_1" class="tab-pane fade in active">

                    <legend  style="color:#8f8f8f"><?= (isset($this->action) && $this->action == 'edit') ? $this->translate('Edit Application') : $this->translate('Create Application Step #1') ?>
                    </legend>

                    <div class="col-md-6 col-md-offset-3">

                        <form action="<?= $this->url('employee', ['action' => 'step-one-check']) ?>" method="post" class="form-step1" enctype="multipart/form-data">
                            <div class="form-group">
                                <label class="control-label application-label" for="position_you_are_applying"><?= $this->translate('Select the position you are applying for') ?>*</label>
                                <select id="position_you_are_applying" name="position_applying" class="form-control application-input">
                                    <option selected> </option>
                                    <option>Part-Time Clerk</option>
                                    <option>Full-Time Clerk</option>
                                    <option>Traveling Clerk</option>
                                    <option>Assistant Manager</option>
                                    <option>Office Manager</option>
                                    <option>Contract Manager</option>
                                    <option>Regional Manager</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label class="control-label application-label" for="location"><?= $this->translate('Location') ?>*</label>
                                <select id="location" name="location" class="form-control application-input">
                                    <option selected> </option>
                                    <option>Branson West</option>
                                    <option>Carthage</option>
                                    <option>Cassville</option>
                                    <option>Clayton</option>
                                    <option>Clinton</option>
                                    <option>Creve Coeur</option>
                                    <option>Des Peres</option>
                                    <option>Eldon</option>
                                    <option>Imperial</option>
                                    <option>Lees Summit</option>
                                    <option>Marshfield</option>
                                    <option>Nevada</option>
                                    <option>Poplar Bluff</option>
                                    <option>Rolla</option>
                                    <option>Springfield</option>
                                    <option>Warrensburg</option>
                                    <option>Union</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label class="control-label application-label" for="area_around"><?= $this->translate('Max distance from home address you are willing to work') ?>*</label>
                                <select id="area_around_field" name="area_around" class="form-control application-input">
                                    <?php foreach ($this->areas as $area) : ?>
                                        <?php /** @var \Application\Model\Area $area */ ?>
                                        <option
                                                value="<?= $area->getId() ?>"
                                            <?= (isset($this->employee) && $this->employee->getAreaAround() !== null && $this->employee->getAreaAround()->getId() === $area->getId()) ? 'selected' : '' ?>
                                        >
                                            <?= $area->getValue() ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </div>

                            <div class="form-group">
                                <label class="control-label application-label" for="worked_mlob"><?= $this->translate('Have you worked in a Missouri License Office Before?') ?>*</label>
                                <select id="worked_mlob" name="worked_mlob" class="form-control application-input">
                                    <option selected> </option>
                                    <option value="1">Yes</option>
                                    <option value="0" >No</option>
                                </select>
                            </div>


                        <div class="form-group">

                            <div style="display: inline-block; float:right" >
                                <button class="btn button-save  step1-next"><span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span> Next</button>
                            </div>
                        </div>
                        </form>

                    </div>



                </div>

                <!-- STEP 2-->
                <div id="step_2" class="tab-pane fade">

                    <legend  style="color:#8f8f8f"><?= (isset($this->action) && $this->action == 'edit') ? $this->translate('Edit Application') : $this->translate('Create Application Step #2') ?>
                    </legend>

                    <div class="col-md-6 col-md-offset-3">

                        <form action="<?= $this->url('employee', ['action' => 'step-two-check']) ?>" method="post" class="form-step2" enctype="multipart/form-data">

                            <div class="form-group">
                                <label class="control-label application-label" for="name_field"><?= $this->translate('First Name') ?>*</label>
                                <input
                                        id="name_field"
                                        name="name" type="text"
                                        class="form-control input-md application-input"
                                        value="<?= isset($this->employee) ? $this->employee->getName() : '' ?>"
                                >
                            </div>

                            <div class="form-group">
                                <label class="control-label application-label" for="surname_field"><?= $this->translate('Last Name') ?>*</label>
                                <input
                                        id="surname_field"
                                        name="surname"
                                        type="text" placeholder=""
                                        class="form-control input-md application-input"
                                        value="<?= isset($this->employee) ? $this->employee->getSurname() : '' ?>"
                                >
                            </div>

                            <div class="form-group">
                                <label class="control-label application-label" for="address_field"><?= $this->translate('Street Address') ?>*</label>
                                <input
                                        id="address_field"
                                        name="address"
                                        type="text"
                                        class="form-control input-md application-input"
                                        value="<?= isset($this->employee) ? $this->employee->getAddress() : '' ?>"
                                >
                            </div>

                            <div class="form-group">
                                <label class="control-label application-label" for="address_field_2"><?= $this->translate('Address Line 2') ?>*</label>
                                <input
                                        id="address_field_2"
                                        name="address_two"
                                        type="text"
                                        class="form-control input-md application-input"
                                        value="<?= isset($this->employee) ? $this->employee->getAddress() : '' ?>"
                                >
                            </div>

                            <div class="form-group">
                                <label class="control-label application-label" for="city_field"><?= $this->translate('City') ?>*</label>
                                <input
                                        id="city_field"
                                        name="city"
                                        type="text"
                                        class="form-control input-md application-input"
                                        value="<?= isset($this->employee) ? $this->employee->getCity() : '' ?>"
                                >
                            </div>

                            <div class="form-group">
                                <label class="control-label application-label" for="state_field"><?= $this->translate('State') ?>*</label>
                                <select
                                        id="state_field"
                                        name="state"
                                        type="text"
                                        class="form-control input-md application-input"
                                >
                                    <option selected></option>
                                    <option value="Alabama">Alabama</option>
                                    <option value="Alaska">Alaska</option>
                                    <option value="Arizona">Arizona</option>
                                    <option value="Arkansas">Arkansas</option>
                                    <option value="CA">California</option>
                                    <option value="CO">Colorado</option>
                                    <option value="CT">Connecticut</option>
                                    <option value="DE">Delaware</option>
                                    <option value="DC">District Of Columbia</option>
                                    <option value="FL">Florida</option>
                                    <option value="GA">Georgia</option>
                                    <option value="HI">Hawaii</option>
                                    <option value="ID">Idaho</option>
                                    <option value="IL">Illinois</option>
                                    <option value="IN">Indiana</option>
                                    <option value="IA">Iowa</option>
                                    <option value="KS">Kansas</option>
                                    <option value="KY">Kentucky</option>
                                    <option value="LA">Louisiana</option>
                                    <option value="ME">Maine</option>
                                    <option value="MD">Maryland</option>
                                    <option value="MA">Massachusetts</option>
                                    <option value="MI">Michigan</option>
                                    <option value="MN">Minnesota</option>
                                    <option value="MS">Mississippi</option>
                                    <option value="MO">Missouri</option>
                                    <option value="MT">Montana</option>
                                    <option value="NE">Nebraska</option>
                                    <option value="NV">Nevada</option>
                                    <option value="NH">New Hampshire</option>
                                    <option value="NJ">New Jersey</option>
                                    <option value="NM">New Mexico</option>
                                    <option value="NY">New York</option>
                                    <option value="NC">North Carolina</option>
                                    <option value="ND">North Dakota</option>
                                    <option value="OH">Ohio</option>
                                    <option value="OK">Oklahoma</option>
                                    <option value="OR">Oregon</option>
                                    <option value="PA">Pennsylvania</option>
                                    <option value="RI">Rhode Island</option>
                                    <option value="SC">South Carolina</option>
                                    <option value="SD">South Dakota</option>
                                    <option value="TN">Tennessee</option>
                                    <option value="TX">Texas</option>
                                    <option value="UT">Utah</option>
                                    <option value="VT">Vermont</option>
                                    <option value="VA">Virginia</option>
                                    <option value="WA">Washington</option>
                                    <option value="WV">West Virginia</option>
                                    <option value="WI">Wisconsin</option>
                                    <option value="WY">Wyoming</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label class="control-label application-label" for="zip_field"><?= $this->translate('ZIP') ?>*</label>
                                <input
                                        id="zip_field"
                                        name="zip"
                                        type="text"
                                        class="form-control input-md application-input"
                                        value="<?= isset($this->employee) ? $this->employee->getZip() : '' ?>"
                                >

                            </div>

                            <div class="form-group">
                                <label class="control-label application-label" for="mobile_phone_field"><?= $this->translate('Cell Phone') ?>*</label>
                                <input
                                        id="mobile_phone_field"
                                        name="mobile_phone"
                                        type="text"
                                        class="form-control input-md application-input"
                                        value="<?= isset($this->employee) ? $this->employee->getMobilePhone() : '' ?>"
                                >
                            </div>

                            <div class="form-group">
                                <label class="control-label application-label" for="landline_number_field"><?= $this->translate('Home Phone') ?></label>
                                <input
                                        id="landline_number_field"
                                        name="landline_phone"
                                        type="text"
                                        class="form-control input-md application-input"
                                        value="<?= isset($this->employee) ? $this->employee->getLandlinePhone() : '' ?>"

                                >
                            </div>

                            <div class="form-group">
                                <label class="control-label application-label" for="email_field"><?= $this->translate('Email') ?>*</label>
                                <input
                                        id="email_field"
                                        name="email"
                                        type="text"
                                        placeholder=""
                                        class="form-control input-md application-input"
                                        value="<?= isset($this->employee) ? $this->employee->getEmail() : '' ?>"
                                >
                            </div>

                            <input
                                    id="latitude"
                                    name="latitude"
                                    type="hidden"
                                    class="form-control input-md application-input"
                                    value="<?= isset($this->coordinate) ? $this->coordinate->getLatitude() : '' ?>"
                            >
                            <input
                                    id="longitude"
                                    name="longitude"
                                    type="hidden"
                                    class="form-control input-md application-input"
                                    value="<?= isset($this->coordinate) ? $this->coordinate->getLongitude() : '' ?>"
                            >

                            <div class="form-group">
                                <div style="display: inline-block">
                                    <div class="btn button-save  step2-prev"><span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span> Previous</div>
                                </div>
                                <div style="display: inline-block; float:right" >
                                    <button class="btn button-save  step2-next"><span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span> Next</button>
                                </div>
                            </div>

                        </form>

                    </div>

                </div>

                <!-- STEP 3-->
                <div id="step_3" class="tab-pane fade">

                    <legend  style="color:#8f8f8f"><?= (isset($this->action) && $this->action == 'edit') ? $this->translate('Edit Application') : $this->translate('Create Application Step #3') ?>
                    </legend>

                    <div class="col-md-6 col-md-offset-3">

                        <form action="<?= $this->url('employee', ['action' => 'step-three-check']) ?>" method="post" class="form-step3" enctype="multipart/form-data">

                            <div class="form-group">
                                <label class="control-label application-label" for="weekly_hours_field"><?= $this->translate('Weekly hours available') ?>*</label>
                                <select id="weekly_hours_field" name="weekly_hours" class="form-control application-input">
                                    <?php foreach ($this->weeklyHours as $weeklyHour) : ?>
                                        <?php /** @var \Application\Model\WeeklyHours $weeklyHour */ ?>
                                        <option
                                                value="<?= $weeklyHour->getId() ?>"
                                            <?= (isset($this->employee) && $this->employee->getWeeklyHoursAvailable() !== null && $this->employee->getWeeklyHoursAvailable()->getId() === $weeklyHour->getId()) ? 'selected' : '' ?>
                                        >
                                            <?= $weeklyHour->getValue() ?>
                                        </option>
                                    <?php endforeach; ?>
                                </select>
                            </div>

                            <div class="form-group ">
                                <label class="control-label application-label" for="start_day_field"><?= $this->translate('Start day') ?>*</label>

                                <div class="input-group date" id="start_day_field_picker">
                                    <input
                                            type="text"
                                            id="start_day_field"
                                            name="start_date"
                                            class="form-control input-md application-input"
                                            value="<?= isset($this->employee) && $this->employee->getStartDate() !== null ? $this->employee->getStartDate()->format('d-m-Y') : '' ?>"
                                    >
                                    <span class="input-group-addon button-save"><i class="glyphicon glyphicon-th"></i></span>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label application-label" for="work_weekends_field"><?= $this->translate('Can you work weekends?') ?>*</label>
                                <select id="work_weekends_field" name="work_weekends" class="form-control application-input">
                                    <option selected> </option>
                                    <option>No</option>
                                    <option>Every other</option>
                                    <option>All </option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label class="control-label application-label" for="customer_service_expierence"><?= $this->translate('Years of customer service expierence') ?>*</label>
                                <select id=customer_service_expierence" name="customer_service_expierence" class="form-control application-input">
                                    <option selected> </option>
                                    <option>less than one</option>
                                    <option>2</option>
                                    <option>3</option>
                                    <option>4</option>
                                    <option>5</option>
                                    <option>6</option>
                                    <option>7</option>
                                    <option>8</option>
                                    <option>9</option>
                                    <option>10+</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label class="control-label application-label" for="business_operations_expierence"><?= $this->translate('Years of business operations expierence') ?>*</label>
                                <select id="business_operations_expierence" name="business_operations_expierence" class="form-control application-input">
                                    <option selected> </option>
                                    <option>less than one</option>
                                    <option>2</option>
                                    <option>3</option>
                                    <option>4</option>
                                    <option>5</option>
                                    <option>6</option>
                                    <option>7</option>
                                    <option>8</option>
                                    <option>9</option>
                                    <option>10+</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label class="control-label application-label" for="management_expierence"><?= $this->translate('Years of management expierence (any level)') ?>*</label>
                                <select id="management_expierence" name="management_expierence" class="form-control application-input">
                                    <option selected> </option>
                                    <option>less than one</option>
                                    <option>2</option>
                                    <option>3</option>
                                    <option>4</option>
                                    <option>5</option>
                                    <option>6</option>
                                    <option>7</option>
                                    <option>8</option>
                                    <option>9</option>
                                    <option>10+</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label class="control-label application-label" for="expierence_word"><?= $this->translate('Years of management expierence with MS Word') ?>*</label>
                                <select id="expierence_word" name="expierence_word" class="form-control application-input">
                                    <option selected> </option>
                                    <option>less than one</option>
                                    <option>2</option>
                                    <option>3</option>
                                    <option>4</option>
                                    <option>5</option>
                                    <option>6</option>
                                    <option>7</option>
                                    <option>8</option>
                                    <option>9</option>
                                    <option>10+</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label class="control-label application-label" for="expierence_exel"><?= $this->translate('Years of management expierence with MS Excel') ?>*</label>
                                <select id="expierence_exel" name="expierence_exel" class="form-control application-input">
                                    <option selected> </option>
                                    <option>less than one</option>
                                    <option>2</option>
                                    <option>3</option>
                                    <option>4</option>
                                    <option>5</option>
                                    <option>6</option>
                                    <option>7</option>
                                    <option>8</option>
                                    <option>9</option>
                                    <option>10+</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label class="control-label application-label" for="expierence_keypad"><?= $this->translate('Years of management expierence with 10-digit keypad') ?>*</label>
                                <select id="expierence_keypad" name="expierence_keypad" class="form-control application-input">
                                    <option selected> </option>
                                    <option>less than one</option>
                                    <option>2</option>
                                    <option>3</option>
                                    <option>4</option>
                                    <option>5</option>
                                    <option>6</option>
                                    <option>7</option>
                                    <option>8</option>
                                    <option>9</option>
                                    <option>10+</option>
                                </select>
                            </div>
                        </form>

                        <div class="form-group">
                            <div style="display: inline-block">
                                <button class="btn button-save  step3-prev"><span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span> Previous</button>
                            </div>
                            <div style="display: inline-block; float:right" >
                                <button class="btn button-save step3-next"><span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span> Next</button>
                            </div>
                        </div>

                    </div>

                </div>


                <!-- STEP 4-->
                <div id="step_4" class="tab-pane fade">


                    <!-- Modal -->
                    <div id="employerModal" class="modal fade" role="dialog">
                        <div class="modal-dialog">
                            <!-- Modal content-->
                            <div class="modal-content">

                                <div class="modal-body">
                                    <p>Потрібно вказати двох роботодавців.</p>
                                </div>
                                <div class="modal-footer">
                                    <button type="button" class="btn button-save" data-dismiss="modal" >Вказати</button>
                                    <button type="button" class="btn btn-danger modal-next"  data-dismiss="modal">Пропустити</button>
                                </div>
                            </div>
                        </div>
                    </div>

                    <legend  style="color:#8f8f8f"><?= (isset($this->action) && $this->action == 'edit') ? $this->translate('Edit Application') : $this->translate('Create Application Step #4') ?>
                        <br>
                        <?= $this->translate('Please provide information for you past two employers') ?>

                    </legend>
                    <div class="row">



                        <div class="employer-result-conteiner col-md-10 col-md-offset-1" style="margin-bottom: 20px; display:none">
                            <table class="employer-resul-table" style="width: 100%">
                                <tr class="employer-tr">
                                    <th class="application-label">
                                        #
                                    </th>
                                    <th class="application-label">
                                        Name
                                    </th>
                                    <th class="application-label">
                                        City
                                    </th>
                                    <th class="application-label">
                                        State
                                    </th>
                                    <th class="application-label">
                                        Years Employed
                                    </th>
                                    <th class="application-label">
                                        Starting Wage
                                    </th>
                                    <th class="application-label">
                                        Ending Wage
                                    </th>
                                    <th class="application-label">
                                        Description
                                    </th>
                                </tr>

                            </table>
                        </div>


                    </div>


                    <div class="row">



                        <form action="<?= $this->url('employee', ['action' => 'step-four-check']) ?>" method="post" class="form-step4" enctype="multipart/form-data">

                            <div class="col-md-6  col-md-offset-3"">

                            <legend  style="color:#8f8f8f"><?= (isset($this->action) && $this->action == 'edit') ? $this->translate('Edit Application') : $this->translate('Employer #') ?>
                                <span class="employer-number-legend"> 1 </span>

                            </legend>

                                <div class="form-group">
                                    <label class="control-label application-label" for="name_field"><?= $this->translate('Name') ?>*</label>
                                    <input
                                            id="name_field"
                                            name="name_ex" type="text"
                                            class="form-control input-md application-input"
                                            value="<?= isset($this->employee) ? $this->employee->getName() : '' ?>"
                                    >
                                </div>

                                <div class="form-group">
                                    <label class="control-label application-label" for="city_field"><?= $this->translate('City') ?>*</label>
                                    <input
                                            id="city_field"
                                            name="city_ex"
                                            type="text"
                                            class="form-control input-md application-input"
                                            value="<?= isset($this->employee) ? $this->employee->getCity() : '' ?>"
                                    >
                                </div>

                                <div class="form-group">
                                    <label class="control-label application-label" for="state_field"><?= $this->translate('State') ?>*</label>
                                    <input
                                            id="state_field"
                                            name="state_ex"
                                            type="text"
                                            class="form-control input-md application-input"
                                            value="<?= isset($this->employee) ? $this->employee->getCity() : '' ?>"
                                    >
                                </div>

                                <div class="form-group">
                                    <label class="control-label application-label" for="years_employed"><?= $this->translate('Years Employed') ?>*</label>
                                    <select id="years_employed_employerse" name="years_employed_ex" class="form-control application-input">
                                        <option selected> </option>
                                        <option>less than one</option>
                                        <option>2</option>
                                        <option>3</option>
                                        <option>4</option>
                                        <option>5</option>
                                        <option>6</option>
                                        <option>7</option>
                                        <option>8</option>
                                        <option>9</option>
                                        <option>10+</option>
                                    </select>
                                </div>

                                <div class="row">
                                    <div class="col-md-6">
                                        <label class="control-label application-label" for="start_day_field"><?= $this->translate('Starting Wage') ?></label>
                                    </div>
                                    <div class="col-md-6">
                                        <label class="control-label application-label" for="start_day_field"><?= $this->translate('Ending Wage') ?></label>
                                    </div>

                                    <div class="" id="sandbox-container">
                                        <div class="input-daterange" id="datepicker">
                                            <div class="col-md-6 form-group">
                                                <input type="text" class="form-control input-md application-input" name="start_ex" style="border-radius: 3px;" value="<?= isset($this->fields['start']) ? ($this->fields['start']) : '' ?>">
                                            </div>
                                            <div class="col-md-6 form-group">
                                                <input type="text" class="form-control input-md application-input" name="end_ex" style="border-radius: 3px;" value="<?= isset($this->fields['end']) ? ($this->fields['end']) : '' ?>">
                                            </div>
                                        </div>
                                    </div>
                                </div>


                                    <div class="form-group">
                                        <label class="control-label application-label" for="commenst_field"><?= $this->translate('Description') ?></label>
                                        <textarea id="commenst_field" name="comments_ex" class="form-control application-input"  rows="4" style="resize: vertical;"><?= isset($this->employee) ? $this->employee->getComments() : '' ?></textarea>
                                    </div>


                                <input type="hidden" name="id_ex" value="0">

                                <button class="btn button-save  form-ex-add"></span> Add</button>

                            </div>

                        </form>
                    </div>



                    <div class="form-group">
                        <div style="display: inline-block">
                            <button class="btn button-save  step4-prev"><span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span> Previous</button>
                        </div>
                        <div style="display: inline-block; float:right" >
                            <button class="btn button-save  step4-next"><span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span> Next</button>
                        </div>
                    </div>
                </div>


                <!-- STEP 5-->
                <div id="step_5" class="tab-pane fade">

                    <legend  style="color:#8f8f8f"><?= (isset($this->action) && $this->action == 'edit') ? $this->translate('Edit Application') : $this->translate('Create Application Step #5') ?>
                    </legend>

                    <div class="col-md-6 col-md-offset-3">


                        <form action="<?= $this->url('employee', ['action' => 'store']) ?>" method="post" class="form-step5" enctype="multipart/form-data">

                            <div class="form-group">
                                <label class="control-label application-label" for="hourly_rate_field"><?= $this->translate('Wage/Pay Expectation (per hour)') ?>*</label>
                                <div class="input-group">
                                    <div class="input-group-addon">$</div>
                                    <input
                                            id="hourly_rate_field"
                                            name="hourly_rate"
                                            type="text"
                                            class="form-control input-md application-input"
                                            value="<?= isset($this->employee) ? str_replace(".", ",", $this->employee->getHourlyRate()) : '' ?>"
                                    >
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="control-label application-label" for="delinquent_or_waived"><?= $this->translate('Are you delinquent or waived from any Missouri tax liabilities?') ?>*</label>
                                <select id="delinquent_or_waived" name="delinquent_or_waived" class="form-control application-input">
                                    <option selected> </option>
                                    <option value="1">Yes</option>
                                    <option value="0">No</option>
                                </select>
                            </div>

                            <div class="form-group">
                                <label class="control-label application-label" for="criminal_background"><?= $this->translate('Are you able to pass a criminal background check?') ?>*</label>
                                <select id="criminal_background" name="criminal_background" class="form-control application-input">
                                    <option selected> </option>
                                    <option value="1">Yes</option>
                                    <option value="0">No</option>
                                </select>
                            </div>


                            <?php if ($this->role === 'admin' || $this->role === 'contributor') :?>
                                <div class="form-group">
                                    <label class="control-label application-label" for="source-field"><?= $this->translate('Application Source') ?>*</label>
                                    <select id="source-field" name="source" class="form-control application-input">
                                        <?php foreach ($this->sources as $source) : ?>
                                            <?php /** @var \Application\Model\Area $source */ ?>
                                            <option
                                                    value="<?= $source->getId() ?>"
                                                <?= (isset($this->employee) && $this->employee->getSourceApplication() !== null && $this->employee->getSourceApplication()->getId() === $source->getId()) ? 'selected' : '' ?>
                                            >
                                                <?= $source->getName() ?>
                                            </option>
                                        <?php endforeach; ?>
                                    </select>
                                </div>
                            <?php else : ?>
                                <input type="hidden" name="source">
                            <?php endif; ?>


                            <?php if (isset($this->id)) : ?>
                                <input type="hidden" name="id" value="<?= $this->id ?>">
                            <?php endif; ?>

                            <?php if (isset($this->action) && $this->action == 'edit') :?>
                                <input type="hidden" name="action" value="edit">
                            <?php endif;?>

                            <button class="btn" style="display:none"></button>



                        </form>









                       <!-- <div align="center">
                            <table border="0" cellpadding="0" cellspacing="0" width="100%">
                                <tr>
                                    <td style="border-bottom: 2px solid #354562; padding: 4px" class="titlec">
                                        <input disabled id="printB" onclick="window.print();" type="button" value="Print Results" name="printB" style="float: right; font-size: 8pt; font-family: Arial"><input onclick="document.getElementById('AfterAction').style.display='none';document.getElementById('expectedArea').style.display='block';document.getElementById('typeArea').style.display='block';document.JobOp.typed.value='';document.JobOp.typed.disabled=false;randNum = Math.floor((Math.random() * 10)) % intToTestCnt;strToTestType = strToTest[randNum];document.JobOp.given.value = strToTestType;" type="button" value="New Test" name="newtest" style="float: right; font-size: 8pt; font-family: Arial">ITS Typing Test System</td>
                                </tr>
                            </table>
                        </div> -->
                        <div class="test-action" data-action="<?= $this->url('employee', ['action' => 'typing-test']) ?>">
                            <table border="0" cellpadding="0" cellspacing="0" width="100%">
                                <tr>
                                    <td style="padding: 4px" class="titlea"  width="4120">
                                        <label class="control-label application-label" ><?= $this->translate('2-Minute Typing Test') ?>*</label>
                                    </td>
                                   <!-- <td style="border-bottom: 1px dotted #8120E36; padding: 4px" class="titlea" background="Images/Lt_Red_Back.gif" width="190">
                                        <p align="right">v1.0</td>-->
                                </tr>
                                <tr>
                                    <td style="padding: 4px" class="bodya" colspan="2">

                                        <FORM name="JobOp">
                                            <table border="0" cellpadding="5" width="100%">
                                                <tr>
                                                    <td>
                                                        <table border="0" cellpadding="5" width="100%">
                                                            <tr>
                                                                <td align="center" class="table-test-th" >
                                                                    <b>Net / Gross WPM</b></td>
                                                                <td align="center" class="table-test-th">
                                                                    <b>Entry Errors</b></td>
                                                                <td align="center" class="table-test-th">
                                                                    <b>Accuracy</b></td>
                                                                <td align="center" class="table-test-th">
                                                                    <b>Elapsed / Remaining</b></td>
                                                            </tr>
                                                            <tr>
                                                                <td align="center">
                                                                    <label class="control-label application-label" >
                                                                        <div id="stat_wpm">Waiting...</div>
                                                                    </label></td>
                                                                <td style="border-left: 1px dotted #8794C7; border-right: 1px dotted #8794C7; border-top-width: 1px; border-bottom-width: 1px" align="center">
                                                                    <label class="control-label application-label" >
                                                                          <div id="stat_errors">Waiting...</div>
                                                                    </label></td>
                                                                <td style="border-left-width: 1px; border-right: 1px dotted #8794C7; border-top-width: 1px; border-bottom-width: 1px" align="center">
                                                                    <label class="control-label application-label" >
                                                                        <div id="stat_score">Waiting...</div>
                                                                    </label></td>
                                                                <td align="center">
                                                                    <label class="control-label application-label" >
                                                                        <div id="stat_timeleft">120</div></td>
                                                                    </label>
                                                            </tr>
                                                        </table>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div id="expectedArea" style="display:block">
                                                            <p style="margin-top: 0; margin-bottom: 0">

                                                                    <textarea name="given" cols=53 rows=10 wrap=on onFocus="deterCPProtect();" class="application-input" style="width: 100%; padding: 5px;border-radius: 5px; ">Click on the button below to start the typing test.  What you will be expected to type will appear here.</textarea>
                                                        </div>
                                                    </td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <p align="center" style="margin-top: 0; margin-bottom: 2px">
                                                            <label class="control-label application-label" >
                                                                attempt #<span class="attempt-test"> 1</span>
                                                            </label> <input type=button value="&gt;&gt; Start Typing Test &lt;&lt;" name="start" onClick="beginTest()" class="button-save "><p align="center" style="margin-top: 0; margin-bottom: 0">
                                                           <input disabled type=button value="&gt;&gt; End Typing Test &lt;&lt;" name="stop" onClick="endTest()" style="display:none; border-left:1px solid #293358; border-right:2px solid #293358; border-top:1px solid #293358; border-bottom:2px solid #293358; width: 100%; background-color: #F05959; color:#FFFFFF;"></td>
                                                </tr>
                                                <tr>
                                                    <td>
                                                        <div id="typeArea" style="display:block">
                                                            <table border="0" width="100%" cellspacing="1">
                                                                <tr>
                                                                    <td style="border: 1px solid #c1e279; background-color: #e6f4e5">
                                                                        <div align="left">
                                                                            <table id="stProg" border="0" width="0%" cellspacing="1">
                                                                                <tr>
                                                                                    <td style="border: 1px solid #c1e279; background-color: #91BF2D; color:#FFFFFF" align="right">
                                                                                        <div id="thisProg">0%</div></td>
                                                                                </tr>
                                                                            </table>
                                                                        </div>
                                                                    </td>
                                                                </tr>
                                                            </table>
                                                            <p style="margin-top: 0; margin-bottom: 0">
                                                                    <textarea onkeypress="doCheck();" onkeydown="//calcStat()" name="typed" cols=53 rows=10 wrap=on class="application-input" style="width: 100%; padding: 5px; border-radius: 5px"></textarea>
                                                        </div>
                                                        <div id="afterAction" style="display:none">

                                                        </div>
                                                    </td>
                                                </tr>
                                                <script>

                                                </script>
                                            </table>
                                        </FORM>
                                    </td>
                                </tr>
                            </table>
                        </div>









                        <div class="form-group">
                            <div style="display: inline-block">
                                <button class="btn button-save  step5-prev"><span class="glyphicon glyphicon-menu-left" aria-hidden="true"></span> Previous</button>
                            </div>
                            <div style="display: inline-block; float:right" >
                                <button class="btn button-save btn-lg step5"><?= (isset($this->action) && $this->action == 'edit') ? $this->translate('Edit') : $this->translate('Save') ?></button>
                            </div>
                        </div>





                    </div>
                </div>
            </div>
        </div>




</div>