<div class="row">
    <div class="col-md-6 col-md-offset-3">
        <form class="" method="post">
            <div class="row">
                <legend  style="color:#8f8f8f">Create employee</legend>
            </div>
            <div class="form-group">
                <label class="control-label application-label" for="name_field">Name</label>
                <input id="name_field" name="" type="text" placeholder="" class="form-control input-md application-input">

            </div>

            <div class="form-group">
                <label class="control-label application-label" for="surname_field">Surname</label>
                <input id="surname_field" name="" type="text" placeholder="" class="form-control input-md application-input">

            </div>

            <div class="form-group">
                <label class="control-label application-label" for="surname_field">Street with number</label>
                <input id="" name="" type="text" placeholder="" class="form-control input-md application-input">

            </div>

            <div class="form-group">
                <label class="control-label application-label" for="zip_field">ZIP</label>
                <input id="zip_field" name="" type="text" placeholder="" class="form-control input-md application-input">

            </div>

            <div class="form-group">
                <label class="control-label application-label" for="city_field">City</label>
                <input id="city_field" name="" type="text" placeholder="" class="form-control input-md application-input">

            </div>

            <div class="form-group">
                <label class="control-label application-label" for="email_field">Email</label>
                <input id="email_field" name="" type="text" placeholder="" class="form-control input-md application-input">

            </div>

            <div class="form-group">
                <label class="control-label application-label" for="experience_field">Experience</label>
                <input id="experience_field" name="" type="text" placeholder="" class="form-control input-md application-input">

            </div>

            <div class="form-group">
                <label class="control-label application-label" for="area_around_field">Area around</label>
                <select id="area_around_field" class="form-control application-input">
                    <option value="1">1 km</option>
                    <option value="5">5 km</option>
                    <option value="10">10 km</option>
                    <option value="20">20 km</option>
                    <option value="30">30 km</option>
                    <option value="">any distance</option>
                </select>
                <span class="help-block">area around home adress willing to work</span>

            </div>

            <div class="form-group">
                <label class="control-label application-label" for="contact_type_field">Type of contact</label>
                <select id="contact_type_field" class="form-control application-input">
                    <option>Minijob</option>
                    <option>Part-time</option>
                    <option>Full-time</option>
                    <option>Self-employed</option>
                </select>

            </div>

            <div class="form-group">
                <label class="control-label application-label" for="weekly_hours_field">Weekly hours available</label>
                <select id="weekly_hours_field" class="form-control application-input">
                    <option value="10">10h</option>
                    <option value="20">20h</option>
                    <option value="30">30h</option>
                    <option value="40">40h</option>
                </select>

            </div>

            <div class="form-group">
                <label class="control-label application-label" for="start_day_field">Start Day</label>
                <input id="start_day_field" name="" type="date" placeholder="" class="form-control input-md application-input">

            </div>

            <div class="form-group">
                <label class="control-label application-label" for="commenst_field">Comments</label>
                <textarea id="commenst_field" name="" class="form-control application-input"  rows="4"></textarea>

            </div>

            <div class="form-group">
                <label class="control-label application-label" for="hourly_rate_field">Hourly rate</label>
                <input id="hourly_rate_field" name="" type="text" placeholder="" class="form-control input-md application-input">

            </div>

            <div class="form-group">
                <label class="control-label application-label" for="driving_licence_field">Driving licence</label>
                <input type="checkbox" name="" id="driving_licence_field" >

            </div>

            <div class="form-group">
                <label class="control-label application-label" for="car_available_field">Car available</label>
                <input type="checkbox" name="" id="car_available_field" >

            </div>

            <div class="form-group">
                <label class="btn button-sign-in btn-file">
                    Upload user photo <input type="file" name="" id="avatar_field" accept="image/*" style="display: none;">
                </label>

                <label class="btn button-sign-in btn-file">
                    Attachments <input type="file" name="" id="attachments-input" accept="image/*" class=""  multiple style="display: none;">
                </label>

            </div>

            <div class="form-group">

                <div class="text-right" >
                    <button class="btn batton-save btn-lg">Save</button>

                </div>
            </div>
        </form>
    </div>
</div>