<div class="row">
    <legend  style="color:#8f8f8f"><?= $this->translate('Create employee'); ?></legend>
    <div class="col-md-6">
        <form action="<?= $this->url('employee', ['action' => 'store']) ?>" method="post" class="async">
            <div class="form-group">
                <label class="control-label application-label" for="name_field"><?= $this->translate('Name') ?>*</label>
                <input id="name_field" name="name" type="text" placeholder="" class="form-control input-md application-input">
            </div>

            <div class="form-group">
                <label class="control-label application-label" for="surname_field"><?= $this->translate('Surname') ?>*</label>
                <input id="surname_field" name="surname" type="text" placeholder="" class="form-control input-md application-input">
            </div>

            <div class="form-group">
                <label class="control-label application-label" for="city_field"><?= $this->translate('City') ?>*</label>
                <input id="city_field" name="city" type="text" placeholder="" class="form-control input-md application-input">
            </div>

            <div class="form-group">
                <label class="control-label application-label" for="address_field"><?= $this->translate('Address') ?>*</label>
                <input id="address_field" name="address" type="text" placeholder="" class="form-control input-md application-input">
            </div>

            <div class="form-group">
                <label class="control-label application-label" for="zip_field"><?= $this->translate('ZIP') ?>*</label>
                <input id="zip_field" name="zip" type="text" placeholder="" class="form-control input-md application-input">
                <button class="btn batton-save btn-sm page-header update-marker"><?= $this->translate('Update marker') ?></button>
            </div>

            <div class="form-group">
                <label class="control-label application-label" for="mobile_phone_field"><?= $this->translate('Mobile phone number') ?>*</label>
                <input id="mobile_phone_field" name="mobile_phone" type="text" placeholder="" class="form-control input-md application-input">
            </div>

            <div class="form-group">
                <label class="control-label application-label" for="landline_number_field"><?= $this->translate('Landline number') ?></label>
                <input id="landline_number_field" name="landline_phone" type="text" placeholder="" class="form-control input-md application-input">
            </div>

            <div class="form-group">
                <label class="control-label application-label" for="email_field"><?= $this->translate('Email') ?>*</label>
                <input id="email_field" name="email" type="text" placeholder="" class="form-control input-md application-input">
            </div>

            <div class="form-group">
                <label class="control-label application-label" for="area_around_field"><?= $this->translate('Area around home address willing to work') ?>*</label>
                <select id="area_around_field" name="area_around" class="form-control application-input">
                    <?php foreach ($this->areas as $area) : ?>
                        <?php /** @var \Application\Model\Area $area */ ?>
                        <option value="<?= $area->getId() ?>"><?= $area->getValue() ?></option>
                    <?php endforeach; ?>
                </select>
            </div>

            <div class="form-group">
                <label class="control-label application-label" for="contact_type_field"><?= $this->translate('Type of contract') ?>*</label>
                <select id="contact_type_field" name="contract_type" class="form-control application-input">
                    <?php foreach ($this->contracts as $contract) : ?>
                        <?php /** @var \Application\Model\Contract $contract */ ?>
                        <option value="<?= $contract->getId() ?>"><?= $contract->getName() ?></option>
                    <?php endforeach; ?>
                </select>
            </div>

            <div class="form-group">
                <label class="control-label application-label" for="weekly_hours_field"><?= $this->translate('Weekly hours available') ?>*</label>
                <select id="weekly_hours_field" name="weekly_hours" class="form-control application-input">
                    <?php foreach ($this->weeklyHours as $weeklyHour) : ?>
                        <?php /** @var \Application\Model\WeeklyHours $weeklyHour */ ?>
                        <option value="<?= $weeklyHour->getId() ?>"><?= $weeklyHour->getValue() ?></option>
                    <?php endforeach; ?>
                </select>
            </div>

            <div class="form-group ">
                <label class="control-label application-label" for="start_day_field"><?= $this->translate('Start day') ?>*</label>

                <div class="input-group date" id="start_day_field_picker">
                    <input type="text" id="start_day_field" name="start_date" class="form-control input-md application-input"><span class="input-group-addon"><i class="glyphicon glyphicon-th"></i></span>
                </div>
            </div>

            <div class="form-group">
                <label class="control-label application-label" for="commenst_field"><?= $this->translate('Comments') ?></label>
                <textarea id="commenst_field" name="comments" class="form-control application-input"  rows="4" style="resize: vertical;"></textarea>
            </div>

            <div class="form-group">
                <label class="control-label application-label" for="hourly_rate_field"><?= $this->translate('Hourly rate') ?>*</label>
                <input id="hourly_rate_field" name="hourly_rate" type="text" placeholder="" class="form-control input-md application-input">
            </div>

            <div class="form-group">
                <label class="control-label application-label" for="experience_field"><?= $this->translate('Experience in the job') ?>*</label>
                <select id="experience_field" name="experience" class="form-control application-input">
                    <option value="1"><?= $this->translate('Yes') ?></option>
                    <option value="0"><?= $this->translate('No') ?></option>
                </select>
            </div>

            <div class="form-group">
                <label class="control-label application-label" for="driving_licence_field"><?= $this->translate('Driving licence') ?>*</label>
                <input type="checkbox" name="driving_license" value="1" id="driving_licence_field" >
            </div>

            <div class="form-group">
                <label class="control-label application-label" for="car_available_field"><?= $this->translate('Car available') ?>*</label>
                <input type="checkbox" name="car_available" value="1" id="car_available_field" >
            </div>

            <div class="form-group">
                <label class="btn button-sign-in btn-file">
                    <?= $this->translate('Upload user photo') ?> <input type="file" name="" id="avatar_field" accept="image/*" style="display: none;">
                </label>

                <label class="btn button-sign-in btn-file">
                    <?= $this->translate('Attachments') ?> <input type="file" name="" id="attachments-input" accept="image/*" class=""  multiple style="display: none;">
                </label>
            </div>

            <div class="form-group">
                <label class="control-label application-label" for="latitude_field"><?= $this->translate('latitude') ?></label>
                <input id="latitude" name="latitude" type="text" placeholder="" class="form-control input-md application-input">
            </div>

            <div class="form-group">
                <label class="control-label application-label" for="longitude_field"><?= $this->translate('longitude') ?></label>
                <input id="longitude" name="longitude" type="text" placeholder="" class="form-control input-md application-input">
            </div>

            <div class="form-group">
                <div class="text-right" >
                    <button class="btn batton-save btn-lg"><?= $this->translate('Save') ?></button>
                </div>
            </div>

        </form>
    </div>
    <div class="col-md-6">
        <div id="map" class="map frame"></div>
    </div>
</div>