<div class="media">
    <div class="media-left">
        <a href="#">
            <img class="media-object" src="<?= $this->basePath($this->employee->getImage()->getThumbnail()) ?>" alt="">
        </a>
    </div>
    <div class="media-body">
        <div class="row">
            <div class="col-sm-6">
                <h4 class="media-heading"><?= $this->employee->getName() ?>&nbsp;<?= $this->employee->getSurname() ?></h4>
                <a href="mailto:<?= $this->employee->getEmail() ?>"><?= $this->employee->getEmail() ?></a>
                <p><span class="glyphicon glyphicon-phone"></span> <?= $this->employee->getMobilePhone() ?></p>
                <p><span class="glyphicon glyphicon-phone-alt"></span> <?= $this->employee->getLandlinePhone() ?></p>
            </div>
            <div class="col-sm-6 text-right">
                <form action="<?= $this->url('employee', ['action' => 'edit']) ?>" method="post">
                    <input type="hidden" name="action" value="edit">
                    <input type="hidden" name="id" value="<?= $this->employee->getId() ?>">
                <button type="submit" class="btn btn-primary edit-profile-modal">Edit</button>
                </form>

            </div>
        </div>
    </div>
    <h4>
        <?= $this->translate('Address') ?>:
        <?= $this->translate('Germany') ?>,
        <?= $this->employee->getCity() ?>,
        <?= $this->employee->getZip() ?>,
        <?= $this->employee->getAddress() ?>
    </h4>
    <h4 class="page-header"><?= $this->translate('Additional information') ?></h4>
    <ul class="list-group">
        <li class="list-group-item">
            <?= $this->translate('Hourly rate') ?>: $<?= $this->employee->getHourlyRate() ?>
        </li>

        <li class="list-group-item">
            <?= $this->translate('Type of contract') ?>: <?= $this->employee->getContract()->getName() ?>
        </li>
        <li class="list-group-item">
            <?= $this->translate('Weekly hours available') ?>: <?= $this->employee->getWeeklyHoursAvailable()->getValue() ?>
        </li>
        <li class="list-group-item">
            <?= $this->translate('Start day') ?>: <?= $this->employee->getStartDate()->format('Y-m-d') ?>
        </li>
        <li class="list-group-item">
            <?= $this->translate('Area around home address willing to work') ?>: <?= $this->employee->getAreaAround()->getValue() ?>
        </li>
        <li class="list-group-item">
            <?= $this->translate('Comment') ?>
            <div class="well">
                <?= $this->employee->getComments() ?>
            </div>
        </li>
        <?php if (true === $this->employee->isExperience()) : ?>
            <li class="list-group-item">
                <?= $this->translate('Has experience') ?>
            </li>
        <?php endif; ?>
        <?php if (true === $this->employee->isCarAvailable()) : ?>
            <li class="list-group-item">
                <?= $this->translate('Car available') ?>
            </li>
        <?php endif; ?>
        <?php if (true === $this->employee->isDrivingLicence()) : ?>
            <li class="list-group-item">
                <?= $this->translate('Driving license present') ?>
            </li>
        <?php endif; ?>
    </ul>
</div>
<hr>
<?= $this->render('layout/concern/comments') ?>
