<div class="comment-edit-block">
    <textarea name="body" id=""  rows="4" class="form-control comment-edit-field"><?= $this->massage ?></textarea>
    <div class="text-right">
        <a class="btn a-dashboard comment-edit-save" data-action-save="<?= $this->url('employee', ['action' => 'comment-edit']) ?>"><span class="glyphicon glyphicon-ok" aria-hidden="true"></span> <?= $this->translate('Save') ?></a>&nbsp;
    </div>
</div>