<nav aria-label="Page navigation">
    <ul class="pagination">
        <?php if ($this->paginator->getCurrentPageNumber() > 1) : ?>
            <li>
                <a href="<?= $this->url($this->route()->getRoute(), $this->route()->getParams(['page' => $this->paginator->getCurrentPageNumber() - 1])) ?>" aria-label="Previous">
                    <span aria-hidden="true">&laquo;</span>
                </a>
            </li>
        <?php endif; ?>
        <?php for ($page = 1; $page <= $this->paginator->count(); $page++) : ?>
            <li class="<?php if ($page === $this->paginator->getCurrentPageNumber()) echo 'active' ?>">
                <a data-page="<?= $page ?>" class="paginator-a"
                    href="<?= $this->url($this->route()->getRoute(), $this->route()->getParams(['page' => $page])) ?>"
                >
                    <?= $page ?>
                </a>
            </li>
        <?php endfor; ?>
        <?php if ($this->paginator->getCurrentPageNumber() < $this->paginator->count()) : ?>
            <li>
                <a href="<?= $this->url($this->route()->getRoute(), $this->route()->getParams(['page' => $this->paginator->getCurrentPageNumber() + 1])) ?>" aria-label="Next">
                    <span aria-hidden="true">&raquo;</span>
                </a>
            </li>
        <?php endif; ?>
    </ul>
</nav>