<ul class="nav nav-pills nav-stacked nav-dashboard">
    <li><a href="<?= $this->url('home') ?>"><span class="glyphicon glyphicon-chevron-left"></span><?= $this->translate('Main') ?></a></li>
    <li><a href="<?= $this->url('dashboard', ['action' => 'index'], ['force_canonical' => true]) ?>"><span class="glyphicon glyphicon-chevron-right"></span><?= $this->translate('Exit from dashboard') ?></a></li>
    <li><a href="<?= $this->url('dashboard', ['action' => 'search'], ['force_canonical' => true]) ?>"><span class="glyphicon glyphicon-chevron-right"></span><?= $this->translate('Search employee') ?></a></li>
    <li><a href="<?= $this->url('dashboard', ['action' => 'overview'], ['force_canonical' => true]) ?>"><span class="glyphicon glyphicon-chevron-right"></span><?= $this->translate('Overview employee') ?></a></li>
    <li><a href="<?= $this->url('dashboard', ['action' => 'areas'], ['force_canonical' => true]) ?>"><span class="glyphicon glyphicon-chevron-right"></span><?= $this->translate('Configure Around Areas') ?></a></li>
    <li><a href="<?= $this->url('dashboard', ['action' => 'contract'], ['force_canonical' => true]) ?>"><span class="glyphicon glyphicon-chevron-right"></span><?= $this->translate('Configure Contract Type') ?></a></li>
    <li><a href="<?= $this->url('dashboard', ['action' => 'source-application'], ['force_canonical' => true]) ?>"><span class="glyphicon glyphicon-chevron-right"></span><?= $this->translate('Configure Source Application') ?></a></li>
    <li><a href="<?= $this->url('dashboard', ['action' => 'reason-removal'], ['force_canonical' => true]) ?>"><span class="glyphicon glyphicon-chevron-right"></span><?= $this->translate('Configure List Why Delete') ?></a></li>
    <li><a href="<?= $this->url('dashboard', ['action' => 'weekly-hours'], ['force_canonical' => true]) ?>"><span class="glyphicon glyphicon-chevron-right"></span><?= $this->translate('Configure Weekly Hours') ?></a></li>
    <li><a href="<?= $this->url('dashboard', ['action' => 'register-keys'], ['force_canonical' => true]) ?>"><span class="glyphicon glyphicon-chevron-right"></span><?= $this->translate('Configure Register keys') ?></a></li>
    <li><a href="<?= $this->url('dashboard', ['action' => 'statistics'], ['force_canonical' => true]) ?>"><span class="glyphicon glyphicon-chevron-right"></span><?= $this->translate('Statistics') ?></a></li>
</ul>