<ul class="nav nav-pills nav-stacked">
    <li><a href="<?= $this->url('dashboard', ['action' => 'index'], ['force_canonical' => true]) ?>"><span class="glyphicon glyphicon-chevron-right"></span><?= $this->translate('Main') ?></a></li>
    <li><a href="<?= $this->url('dashboard', ['action' => 'search'], ['force_canonical' => true]) ?>"><span class="glyphicon glyphicon-chevron-right"></span><?= $this->translate('Search employee') ?></a></li>
    <li><a href="<?= $this->url('dashboard', ['action' => 'areas'], ['force_canonical' => true]) ?>"><span class="glyphicon glyphicon-chevron-right"></span><?= $this->translate('Configure Around Areas') ?></a></li>
</ul>