<divclass="collapse navbar-collapse">
    <ul class="nav navbar-nav">
        <li class="active"><a href="<?= $this->url('home') ?>"><?= $this->translate('Home') ?></a></li>
    </ul>
    <a href="<?= $this->url('user', ['action' => 'login']) ?>" class="btn button-sign-on navbar-btn navbar-right" ><?= $this->translate('Sign In') ?></a>
    <a href="<?= $this->url('user', ['action' => 'register']) ?>" class="btn button-sign-on navbar-btn navbar-right" ><?= $this->translate('Sign Up') ?></a>
    <?= $this->render('layout/translate/switcher.phtml') ?>
</div>