<div class="collapse navbar-collapse">
    <ul class="nav navbar-nav">
        <li class="active"><a href="<?= $this->url('home') ?>"><?= $this->translate('Home') ?></a></li>
    </ul>
    <a href="<?= $this->url('employee', ['action' => 'dashboard']) ?>" class="btn button-sign-on navbar-btn navbar-right" ><?= $this->translate('Dashboard') ?></a>
    <a href="<?= $this->url('employee', ['action' => 'search']) ?>" class="btn button-sign-in navbar-btn navbar-right" style="margin-right: 10px;"><?= $this->translate('Search') ?></a>
    <?= $this->render('layout/translate/switcher.phtml') ?>
</div>